services:
  verifier-team:
    image: wooss97/bitvmx-verifier:latest
    container_name: bitvmx-verifier-team
    ports:
      - "9080:80"
    volumes:
      - .:/bitvmx-backend
    env_file:
      - .env_verifier
      - .env_common
    networks:
      - bitvmx-net-team

  prover-team:
    image: wooss97/bitvmx-prover:latest
    container_name: bitvmx-prover-team
    ports:
      - "9081:80"
    volumes:
      - .:/bitvmx-backend
    env_file:
      - .env_prover
      - .env_common
    networks:
      - bitvmx-net-team

networks:
  bitvmx-net-team:
    driver: bridge