services:
  prover-backend:
    # Use pre-built image from Docker Hub instead of building locally
    image: wooss97/bitvmx-prover:latest
    container_name: bitvmx-prover
    env_file:
     - .env_prover
    volumes:
      - type: bind
        source: .
        target: /bitvmx-backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8081:80"
    networks:
      - bitvmx-net

  verifier-backend:
    # Use pre-built image from Docker Hub instead of building locally
    image: wooss97/bitvmx-verifier:latest
    container_name: bitvmx-verifier
    env_file:
     - .env_verifier
    volumes:
      - type: bind
        source: .
        target: /bitvmx-backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:80"
    networks:
      - bitvmx-net

  bitcoin-regtest-node:
    image: kylemanna/bitcoind
    ports:
      - "8443:8443"
    networks:
      - bitvmx-net
    volumes:
      - type: bind
        source: regtestbitcoin.conf
        target: /bitcoin/.bitcoin/bitcoin.conf

networks:
  bitvmx-net: