services:
  prover-backend:
    image: wooss97/bitvmx-prover:latest
    env_file:
     - .env_common
     - .env_prover
    environment:
      - STEP_FEES_SATOSHIS=7000
      - HASH_FEES_SATOSHIS=60000
      - CHOICE_FEES_SATOSHIS=4000
      - TRIGGER_FEES_SATOSHIS=7000
      - INITIAL_AMOUNT_SATOSHIS=100000
      - BITVMX_DIGIT_BITS=8
    volumes:
      - type: bind
        source: .
        target: /bitvmx-backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:80"
    command: uvicorn prover_app.main:app --host 0.0.0.0 --port 80 --timeout-keep-alive 1800 --reload
    networks:
      - bitvmx-net

  verifier-backend:
    image: wooss97/bitvmx-verifier:latest
    env_file:
     - .env_common
     - .env_verifier
    volumes:
      - type: bind
        source: .
        target: /bitvmx-backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8081:80"
    command: uvicorn verifier_app.main:app --host 0.0.0.0 --port 80 --timeout-keep-alive 1800 --reload
    networks:
      - bitvmx-net

networks:
  bitvmx-net: