services:
  prover-backend:
    image: wooss97/bitvmx-prover:latest
    env_file:
     - .env_common
     - .env_prover
    environment:
      - STEP_FEES_SATOSHIS=3000
      - HASH_FEES_SATOSHIS=3000
      - CHOICE_FEES_SATOSHIS=1000
      - TRIGGER_FEES_SATOSHIS=3000
      - INITIAL_AMOUNT_SATOSHIS=100000
    volumes:
      - type: bind
        source: .
        target: /bitvmx-backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:80"
    networks:
      - bitvmx-net

  verifier-backend:
    image: wooss97/bitvmx-verifier:latest
    env_file:
     - .env_common
     - .env_verifier
    volumes:
      - type: bind
        source: .
        target: /bitvmx-backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8081:80"
    networks:
      - bitvmx-net

  bitcoin-regtest-node:
#    build:
#      context: .
#      target: kylemanna/bitcoind
    image: kylemanna/bitcoind
    ports:
      - "8443:8443"
    networks:
      - bitvmx-net
    volumes:
      - type: bind
        source: regtestbitcoin.conf
        target: /bitcoin/.bitcoin/bitcoin.conf
#    volumes:
#      - type: bind
#        source: ./bitcoin_data
#        target: /root/.bitcoin

  format:
    build:
      context: .
      target: bitvmx-base
    image: bitvmx-base
    volumes:
      - type: bind
        source: .
        target: /bitvmx-backend
    entrypoint: sh -c "black --config .black . && ruff check --fix"

  flake8:
    image: bitvmx-base
    volumes:
      - type: bind
        source: ./
        target: /bitvmx-backend
        read_only: true
    entrypoint: flake8

  black:
    image: bitvmx-base
    volumes:
      - type: bind
        source: ./
        target: /bitvmx-backend
        read_only: true
    entrypoint: black --config .black --check --diff .

networks:
  bitvmx-net: